OpenNMS/grafana-plugin

- Dockerfile
- README.md
- docker-compose.yml
Build the Grafana OpenNMS Helm App with Docker based on the official Grafana image. Allow user to specify a GitHub URL and a branch reference for the build. Added documentation and created a sample docker-compose file to build a whole service stack using exisiting PostgreSQL and OpenNMS Horizon images.
> Add Docker build and documentation

- .gitignore
- makerpm.js
- package.json
- src/rpm/spec.mustache
- yarn.lock
This PR adds a script to generate an RPM package in `dist/packages/`.  If you want to test, it works fine with Homebrew's RPM.
> HELM-7: create an RPM package from the Helm app

- Dockerfile
Upgrade to use latest Grafana stable version 4.6.0 instead of 4.4.1.
> HELM-68: Bump grafana base image 4.4.1 -> 4.6.0

- docs/installation/debian.adoc
- docs/installation/plugin.adoc
- docs/installation/rpm.adoc
- docs/installation/source.adoc
As discussed I added it into the installation section. But I don't like to have it 4 times in the docs.
What do you think? Other suggestions?
https://issues.opennms.org/browse/HELM-75
> HELM-75: required Grafana version is missing

- package.json
- src/components/timeout.html
- src/components/timeout.js
- src/datasources/fault-ds/module.js
- src/datasources/fault-ds/partials/config.html
- src/datasources/flow-ds/module.js
- src/datasources/flow-ds/partials/config.html
- src/datasources/perf-ds/datasource.js
- src/datasources/perf-ds/module.js
- src/datasources/perf-ds/partials/config.html
- src/lib/client_delegate.js
- yarn.lock
This PR builds on [HELM-78](https://github.com/OpenNMS/opennms-helm/pull/49) to add configurable timeout support to the Helm datasources.
> HELM-86: add support for configurable timeouts

- src/datasources/perf-ds/datasource.js
- src/datasources/perf-ds/partials/query.editor.html
- src/datasources/perf-ds/query_ctrl.js
Pretty straightforward, this PR implements support for `fallback-attribute` in the performance datasource.  I confirmed it by typo-ing the attribute and then providing a valid value (`ifInOctets`) for the `fallback-attribute` and I still get graphs, so it seems to be working as expected.  :)
> HELM-87: implement fallback-attribute in grafana perf-ds

- src/datasources/perf-ds/datasource.js
This PR fixes the PM datasource to properly return a rejection when the request fails.  It also tweaks the failure object so it provides a bit more data in the inspector.
> HELM-88: fix PM datasource failure handling

- package.json
- yarn.lock
This PR fixes a bug where Helm shows an error if there are no exporters when queried.  It also includes a build fix for OSX.
> HELM-91: fix errors when there are no exporters

- src/plugin.json
This PR changes the `plugin.json` description to be shorter so it fits nicely in the summary box on the Grafana plugin registry page.  Currently they cut it off with `...`:
> simplify plugin summary to fit the plugin registry page

- src/datasources/perf-ds/interpolate.js
The String.replace() function only replaces the first occurence of a found element, when used with a substring as parameter. I changed the parameter to a RegExp to replace all occurences of template variables.
> HELM-97: Fix for "Template variable were only replaced once"

- src/datasources/perf-ds/datasource.js
- src/datasources/perf-ds/partials/config.html
- src/datasources/perf-ds/plugin.json
This commit adds support for setting a global time interval for the PM datasource and optionally overriding it per query. Max datapoints can also be specified per query.
Allowing a global default is useful when the minimum_step setting in OpenNMS is lower than what you'd want to use for most graphs. (For example when polling certain services every 60 seconds, but everything else at a larger interval.)
One new configuration option for the PM datasource:
Two new graph query options:
> HELM-100: allow overriding time intervals and max datapoints

- src/datasources/perf-ds/datasource.js
- JIRA: https://issues.opennms.org/browse/HELM-101
Instead of displaying errors on all freshly initialized panels:
... return an empty 'data' array, and let Grafana inform the user that there isn't any data available (yet):
> HELM-101: avoid initialization errors

- src/datasources/perf-ds/partials/query.editor.html
- src/datasources/perf-ds/query_ctrl.js
- src/spec/test-main.js
- JIRA: https://issues.opennms.org/browse/HELM-71
This is a new attempt at fixing the behaviour of validateTarget(), updated to work with Helm 2.0.
This commit displays the error messages from validateTarget() to the user, instead of silently submitting API requests that are expected to fail:
The commit also marks relevant input elements as required, which some browsers may visualise to the user:
> HELM-71: display errors for incomplete queries

- .gitignore
- Dockerfile
- README.md
- package.json
- src/panels/alarm-table/column_options.html
- src/panels/alarm-table/column_options.js
- src/panels/alarm-table/editor.html
- src/panels/alarm-table/module.html
- src/panels/alarm-table/module.js
- src/panels/alarm-table/renderer.js
- src/panels/alarm-table/sass/table.scss
- src/panels/alarm-table/table_model.js
This PR changes the `TableRenderer` to treat "severity" as a first-class type, like number or date columns.
* bump version to 3.0.0 because of breaking config change
* remove config option for "Severity icon"
* add column type "severity"
* add support for configuring severity column type (icon, label, upper-case label)
* add support for sorting the severity column
* add a mouseover to the severity icon
> HELM-62: make "Severity" a column type

- src/panels/alarm-table/column_options.html
- src/panels/alarm-table/editor.html
- src/panels/alarm-table/editor.js
- src/panels/alarm-table/renderer.js
This PR makes the color-coding for severity configurable to either be `Row` (the entire row, like the current impl when checked), `Column` (just any column with `type='severity'`), or `Off` (like the current impl, when unchecked).
This PR relies on changes made in https://github.com/OpenNMS/opennms-helm/pull/68
> HELM-99: make severity color coding column or row

- src/datasources/fault-ds/datasource.js
- src/spec/fault_ds_datasource_spec.js
This PR fixes the `fault-ds` so it turns a `node=foreignSource:foreignId` criteria from a template variable into a separate set of criterias for foreign source and foreign ID.
Note: it does _not_ solve the (probably common) issue of wanting to multi-select nodes.  That will require additional work.
> HELM-73: make $node template variable work in alarm queries

- src/datasources/fault-ds/datasource.js
- src/spec/fault_ds_datasource_spec.js
- src/spec/template_srv.js
This PR adds support for multi-select variables in the alarm table.  Tested with `node` and `severity` columns.
> HELM-105: handle multi-select variables

- src/dashboards/flow_deep_dive.json
Distinguish transferred bytes per second and total amount of transferred data in the given time frame by distinguish "Throughput" and "Data Usage". Added unit labels for "bytes/sec" in time series graphs for throughput. Additionally changed the Errors and Discards from SNMP MIB-2 to packets/sec referred to https://www.ietf.org/rfc/rfc1213.txt
Set legend as a table with min/max/avg and set default to sort avg descending to allow users to identify relevant throughput to filter.
* JIRA: https://issues.opennms.org/browse/HELM-106
> HELM-106: Improve naming and axis labels

- src/panels/alarm-table/alarm_details.html
- src/panels/alarm-table/alarm_details.js
- src/panels/alarm-table/module.js
- src/panels/alarm-table/sass/colors.scss
- src/panels/alarm-table/sass/table.dark.scss
- src/panels/alarm-table/sass/table.light.scss
- src/panels/alarm-table/sass/table.scss
- src/plugin.json
This PR introduces a thin box around grouped node alarms in the alarm details view, to resolve feedback on the issue.  It also fixes a couple of other tiny layout/color bugs I found while working on the issue.
> HELM-121: additional layout/theme fixes

- .jshintrc
- src/datasources/perf-ds/datasource.js
- src/datasources/perf-ds/function_formatter.js
- src/datasources/perf-ds/query_ctrl.js
- src/spec/perf_ds_label_formatter_spec.js
This PR adds support for formatting labels based on metadata returned by Meridian 24 and later. (The backend changes are in [this pull request](https://github.com/OpenNMS/opennms/pull/2318).)
It adds support for the following "functions" to be used in the label field:
* `nodeToLabel(<nodeId|foreign-source:foreign-id>)`: the associated node's label
* `resourceToLabel(<nodeCriteria|resourceId>[, partialResourceId])`: the resource's label
* `resourceToName(<nodeCriteria|resourceId>[, partialResourceId])`: the resource's name
* `resourceToInterface(<nodeCriteria|resourceId>[, partialResourceId])`: the interface name
The resource functions can accept either a single argument containing a complete resource ID (`node[situation-test:nodeb].interfaceSnmp[en0-000123456789]`), or two arguments of a …
> HELM-84: support formatting of values from `nodeFilter` and `nodeResources`

- src/datasources/perf-ds/datasource.js
- src/spec/perf_ds_datasource_spec.js
JIRA: https://issues.opennms.org/browse/HELM-129
Here we set `relaxed=true` by default in the queries to the Measurements API. This allows queries to be processes that contain series which are not present.
I opted to always keep this enabled as opposed to adding another flag to enable/disable it.
> HELM-129: Use the Measurements API in relaxed mode

- src/panels/alarm-table/renderer.js
- JIRA: https://issues.opennms.org/browse/HELM-134
HELM-118 broke Grafana's internal date functionality + dashboard reloading when using custom time ranges combined with a dashboard containing an Alarm Table panel.
By using defineLocale() instead of updateLocale(), custom date ranges in Grafana work fine even when using the Alarm Table.
> HELM-134: Define 'en-short' instead of trying to update it

- src/panels/alarm-table/renderer.js
Simple change, adds a `title=""` tag to the `<td>`s in the alarm table if the (raw) value is a string.  This allows seeing the full value even if you've configured the column to have a fixed width.
> HELM-143: add a title="" tag to string values for mouse-over

- package.json
- src/panels/alarm-table/alarm_details.html
- src/panels/alarm-table/alarm_details.js
- src/panels/alarm-table/sass/_table.scss
- yarn.lock
This PR consists of the HELM UI work to allow a user to select ONE of the related alarms as the 'root cause' of the Situation.
This information is passed via opennms-js/ReST to the OpenNMS server and then persisted in ElasticSearch.
Additionally, a user can provide a list of 'Tags' that will be attached to each situation/alarm feedback record.
This PR also offers a different style on the feedback buttons in conjunction with the new RootCause button.
That said, there is probably lots of room for improvement, so all suggestions are welcome.
JIRA: https://issues.opennms.org/browse/HZN-1492
Currently, the UI looks like this:
> HZN-1492 Tag "root cause" alarm when providing feedback

- package.json
- src/panels/alarm-table/alarm_details.html
- src/panels/alarm-table/editor.html
- src/panels/alarm-table/editor.js
- src/panels/alarm-table/module.html
- src/panels/alarm-table/sass/_severity-themes.scss
- src/panels/alarm-table/sass/_table.scss
- yarn.lock
This PR adds theme support for alarm table severities.  It has 3 default themes: "Helm Default" (existing helm theme), "OpenNMS" (matches OpenNMS Horizon 24's colors), and "OMi".
> HELM-149: theme support for alarm table severities

- src/panels/alarm-table/alarm_details.html
- src/panels/alarm-table/module.js
- src/panels/alarm-table/sass/_table.scss
This patch also does a couple of other small layout cleanups while I was in this code.
* make the modal dynamically re-size itself vertically (previously, it would set the max height at popup time, but then if the window was resized, it wouldn't adjust)
* make the "severity" row in the details view colorized
* fix the JSON tab to not waste extra space and do nicer scroll bar boundaries
> HELM-147: wrap log/description/operinst

- src/datasources/flow-ds/add_opennms_func.js
- src/datasources/flow-ds/datasource.js
- src/datasources/flow-ds/flow_functions.js
- src/datasources/flow-ds/func_editor.js
- src/datasources/flow-ds/partials/query.editor.html
- src/datasources/flow-ds/query_ctrl.js
- src/lib/client_delegate.js
Drift 2.0 API Enhancements Frontend Work
This PR updates Helm to provide filtering based on the enhanced flow API in Opennms.
Filtering based on host:
Filtering based on application:
Filtering based on conversation key:
The new filter functions are only presented when the appropriate segment/metric is selected (application, host, conversation).
Autocomplete is presented for the host and application filters. The autocomplete takes into account the context of the time range currently selected as well as the exporter node and interface Ids if set.
For conversation filtering it is expected that this will be set in the future by a dynamically populated variable and there is no auto complete currently.
I've tested this manually for all the filtering cases for the graphed data as well as the …
> HZN-1559,HZN-1570,HZN-1571: Drift 2.0 API Enhancements Frontend Work

- docs/datasources/flow_datasource.adoc
- src/datasources/flow-ds/add_opennms_func.js
- src/datasources/flow-ds/datasource.js
- src/datasources/flow-ds/flow_functions.js
- src/spec/test-main.js
- Allow user to override the step to group results by a given interval in string format (10s, 5m, 1h etc...)
- Added cardinality to functions to prevent those that are to be applied only once from being presented in the menu after already being applied
- Added mutual exclusions to functions to prevent conflicting functions from being applied (such as topN and withApplication)
This screenshot shows the new transform function to apply the interval `withGroupByInterval` and the function being excluded from the menu due to cardinality of single.
* Temporarily based on top of the other drift2.0 work, will re-target when that is in
Jira: https://issues.opennms.org/browse/HELM-148
> HELM-148: Control resolution when using the flow datasource

- src/datasources/flow-ds/datasource.js
This PR fixes an issue introduced by my previous PR where template variable substitution stopped working for functions that took int values.
> Bug Fix - Template variable substitution was broken for int functions

- src/panels/flow-histogram/ctrl.js
- webpack.config.js
This fixes a bug where the Pie Chart panel can't be used on the same dashboard as the Flow Histogram panel.
The histogram panel appears to be working properly after these changes.
> Use the provided version of Flot instead of pulling in our own.

- src/panels/flow-histogram/ctrl.js
The text and case for some of the column labels has changed for the table data that is returned by the flow rest API. This PR includes changes to be compatible with the new columns as well as makes lookups case insensitive.
Tested against latest OpenNMS develop (including the hostname resolution work).
No Jira.
> Update flow panel to be compatible with changes related to the hostname resolution work

- .circleci/config.yml
- package.json
- src/panels/flow-histogram/ctrl.js
- src/spec/test-main.js
HELM-163: Enhance CircleCI workflow to capture test metadata for Helm
* Add two new script targets "eslint-circleci" and "test-circleci" for circleci tests
* Convert mocha tests to output for circleci capture
* Convert eslint tests to output for circleci capture
JIRA: https://issues.opennms.org/browse/HELM-163
> HELM-163: Enhance CircleCI workflow to capture test metadata for Helm

- src/datasources/entity-ds/AlarmEntity.js
- src/lib/client_delegate.js
- src/panels/filter-panel/editor.js
- src/panels/filter-panel/value_select_dropdown.js
- yarn.lock
> JS-41: fix Helm `develop` with latest OpenNMS.js changes

- src/datasources/entity-ds/AlarmEntity.js
- src/spec/alarm_entity_spec.js
JIRA: https://issues.opennms.org/browse/HELM-175
With these changes processing 5000 alarms with 100 event parameters each
goes from taking 67631ms to 799ms (85x faster).
> HELM-175: Use hasOwnProperty instead of _.has to improve performance

- src/datasources/flow-ds/datasource.js
- src/panels/flow-histogram/ctrl.js
This PR makes a small change to fix calls to `toBits` when configuring the histogram panel.
> HELM-190: fix coercion of toBits when  vars is not set yet

- .circleci/config.yml
- docs/_distro_map.yml
- docs/_stylesheets/helm.css
With this change, we add build steps to our CI/CD pipeline to build the documentation with CircleCI and publish it to netlify. The HELM docs are published to https://opennms-helm-doc.netlify.com.
The publishing job trigger is filtered when we push to the master branch and when version number tags are pushed. To test the pipeline, I had to add the jira/helm-216 branch additionally to master to test if the pipeline works. We have to remove the a) branch filter in CircleCI and b) remove the branch in the distro file for Asciibinder before …
> HELM-216: Build docs with CircleCI and publish docs to Netlify

- .circleci/config.yml
Created two build jobs to build DEB and RPM packages. Added the Cloudsmith orb to publish it to our [repository](https://cloudsmith.io/~opennms/repos/common/packages/). The Cloudsmith ORB requires the CLOUDSMITH_API_KEY environment variable to be set on the project.
We create RPM and DEB packages in the `dist/packages` directory. In the `make-deb` and `make-rpm`, I've just set to store everything in the dist/packages dir see:
```yaml
- store_artifacts:
path: ./dist/packages
```
There is no wildcard support in the store_artifacts directive …
> HELM-214/HELM-222: Publish build artifacts with CircleCI to Cloudsmith

- .circleci/config.yml
This PR for [HELM-233](https://issues.opennms.org/browse/HELM-233) builds on @indigo423's work on auto-branch-merging to make it configurable at the top of the circle config rather than hardcoding branch names throughout the yaml.  It also updates to using the latest signing orb and fixes a few formatting issues.
For an example of a working merge, I original set the variables to merge from `jira/HELM-233` to `jira/HELM-233-master` to simulate a develop -> master merge.  You can see the example runs here:
* [jira/HELM-233 (create-merge-branch)](https://app.circleci.com/pipelines/github/OpenNMS/opennms-helm/126/workflows/59167228-c983-47e8-99a5-7cbbaca77211/jobs/4114)
* [merge/jira-HELM-233-to-jira-HELM-233-master (merge-branch)](https://app.circleci.com/pipelines/github/OpenNMS/opennms-helm …
> HELM-233: auto-merge develop to master

- src/lib/filter_column.js
- src/lib/query_variable.js
- src/lib/text_box_variable.js
- src/lib/utils.js
- src/panels/alarm-table/module.js
- src/panels/filter-panel/ctrl.js
- src/panels/filter-panel/editor.html
- src/panels/filter-panel/editor.js
- src/panels/filter-panel/module.html
This is incredibly gross, but I got it all working on Grafana 6 as well as Grafana 7 (I tested with 6.7.3, 7.1.0 and 7.2.0)
* port over variable-management code from Grafana 6.7
* disable ad-hoc queries in Grafana 7 (I _think_ we don't actually mark any columns as filterable anyway, so this should be a no-op, in theory)
* cleanups to the filter panel layout to fit Grafana 7's right-side tray format
* debounce input to text fields in the filter panel
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-247
> HELM-247: fix alarm table and filter on Grafana 7

- src/datasources/entity-ds/query_ctrl.ts
- src/datasources/flow-ds/datasource.js
- src/datasources/flow-ds/query_ctrl.ts
- src/datasources/perf-ds/query_ctrl.ts
The `target` member is already set when the constructor is called. Do not overwrite its value by member initializers.
> do not initialize 'target' member of query controllers

- src/datasources/entity-ds/datasource.ts
Small change to not limit the number of search property results.  This _shouldn't_ be too bad since the search API doesn't send a large payload per entry.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-274
> HELM-274: do not limit the number of properties

- src/datasources/entity-ds/NodeEntity.ts
- src/lib/client_delegate.ts
This PR adds support for querying by `snmpPrimary` and displaying `ifIndex` and primary IP address.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-188
> HELM-188: add support for IP ifIndex and primary IP address

- docs/modules/datasources/pages/flow_datasource.adoc
- src/datasources/entity-ds/Entity.ts
- src/datasources/entity-ds/datasource.ts
- src/datasources/flow-ds/datasource.ts
- src/lib/client_delegate.ts
- src/test/entity_ds_datasource.spec.ts
- src/test/flow_ds_datasource.spec.ts
Issue: https://issues.opennms.org/browse/HELM-299
This PR lifts the restriction that only a single query is allowed for a panel.
* In case of time series, no additional actions are necessary: Grafana graphs all the time series in the graph panel.
* In case of summary tables, Grafana's `Merge` transformation can be used to merge several tables into a single table
In addition, this PR removes some legacy dependencies on Angular. In particular, current Grafana versions do no longer require the usage of Angular's `IPromise` but support the usage of the standard `Promise`.
> HELM-299: support multiple flow queries per panel

- src/datasources/flow-ds/datasource.ts
Just found that we did not support the `hide` flag of queries.
> support query hide flag

- .circleci/config.yml
- docs/modules/datasources/pages/performance_datasource.adoc
- src/datasources/perf-ds/constants.ts
- src/datasources/perf-ds/datasource.ts
- src/datasources/perf-ds/partials/query.editor.html
- src/datasources/perf-ds/partials/query.options.html
- src/datasources/perf-ds/query_ctrl.ts
Issue: https://issues.opennms.org/browse/HELM-293
This PR adds support for querying string properties to the performance datasource.
@Bonrob2 I also added some documentation; please review.
Open question: I added some help text into `query.options.html` but did not find where this would show up when using the performance datasource. Is the help functiionality broken?
> HELM-293: support string properties in performance datasource

- docs/modules/datasources/pages/flow_datasource.adoc
- src/datasources/flow-ds/datasource.ts
- src/datasources/flow-ds/flow_functions.ts
- src/test/flow_ds_datasource.spec.ts
I believe the issue was a bug in the flows datasource for series(Nan values were actual string NaN, so Number.isNaN was retruning incorrect values). There is no need to create a Transformation for filter NaN unless is for an especific scenario where this grouping is needed.
Reduce Expression should be able to use Number type values from the flow series datasoiurces.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-305
> AR/jira/HELM-305: Helm's Flow datasource cannot filter "NaN" results, breaking Grafana reduce expressions

- src/datasources/perf-ds/datasource.ts
- src/lib/utils.ts
- src/test/perf_ds_datasource.spec.ts
Added functionlity to allow Glob expressions ('*' and '|' )in order to query multiple resources and attributes from the performance datasource using a single query. (See images below with result samples)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-309
> HELM-309: Grafana Datasource expressions - Performance

- src/datasources/flow-ds/datasource.ts
- src/test/flow_ds_datasource.spec.ts
Possible fix for missing records when using combineIngressEgress transformation
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-320
> HELM-320: FlowDS's combineIngressEgress transform loses the first query response result

- src/lib/text_box_variable.ts
- src/lib/utils.ts
HELM-272: Fix issues found while fixing HELM-272 which were causing FilterPanel not to update correctly
This needs to be done in conjunction with OpenNMS/opennms HELM-272, [PR](https://github.com/OpenNMS/opennms/pull/4958)
- In `lib/utils.ts`, `variableUpdated`, sometimes variables don't have `updateOptions` method defined, so check first
- In 'lib/utils.ts', added `getValueOrFirstElement()` since sometimes Grafana returns values that are either the raw value or else a one-element array with the value
- In `lib/text_box_variable.ts`, use `getValueOrFirstElement` to prevent `.trim() not found` error 
These issues were preventing Filter value dropdowns/text boxes to appear on Filter Panel
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-272
* Continuous Integration: …
> HELM-272: Fix issues found while fixing HELM-272

- docs/modules/datasources/pages/performance_datasource.adoc
- src/datasources/perf-ds/datasource.ts
Added a new regex attribute to nodeResources template variable function to allow filtering by textProperties when they are used.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-332
> HELM-332: HELM: Regex for Grafana Template Variable does not work on labels [Performance Datasource]

- src/datasources/entity-ds/datasource.ts
Fixed the issue with the filter creation when using nodeFilter.
It should filter by passing \<attribute\>='\<value\>' as an argument. And value should be able to be a constant and variable (template_variable)
Now should be able to handle scenarios like 
nodeFilter(location='$location')
and 
nodeFilter(location='Kanata')
nodeFilter(foreignId='$foreignId')
and 
nodeFilter(foreignId='0.0.0.0')
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-338
> HELM-338: Entity nodeFilter is not working

- site.yml
NMS-14666: update all doc repos with link to new Antora UI bundle: updated the HLEM repo so that the site.yml file includes link to current Antora UI bundle.
At that …
> NMS-14666: Update all doc repos with link to new Antora UI bundle

- src/datasources/flow-ds/datasource.ts
- src/lib/utils.ts
fixed issue when passing FS:FSID instead of node id to flows Interface function interfacesOnExporterNodeWithFlows()
Refactored Promises to use async/await in flows datasource
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-336
> HELM-336: Flow DS query interfacesOnExporterWithFlows() does not accept FS:FID as argument

- docs/modules/datasources/pages/entity_datasource.adoc
- docs/modules/datasources/pages/flow_datasource.adoc
- src/datasources/entity-ds/datasource.ts
- src/datasources/flow-ds/datasource.ts
- src/lib/utils.ts
Allow multiple attribute/value pair filters and values also allow regular expressions
Flows DS
Example: exporterNodesWithFlows(location='$location' & label='.\*com.*')
Also allow multiple attribute/value filters for the nodeFilter function in Entities DS. This one doesn't accept Regex yet since that is done on the backend.
Entity DS now also would work with 
nodeFilterlocation='$location' & label='localhost')
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-337
> HELM-337: exporterNodesWithFlows() query handles criteria differently than other queries

- src/datasources/entity-ds-react/EntityDataSource.ts
- src/datasources/entity-ds-react/EntityHelper.tsx
- src/datasources/entity-ds-react/queries/attributeMappings.ts
- src/datasources/entity-ds-react/queries/index.ts
- src/datasources/entity-ds-react/queries/queryAlarms.ts
- src/datasources/entity-ds-react/queries/queryIPInterfaces.ts
- src/datasources/entity-ds-react/queries/queryMonitoredServices.ts
- src/datasources/entity-ds-react/queries/queryNodes.ts
- src/datasources/entity-ds-react/queries/queryOutages.ts
- src/datasources/entity-ds-react/queries/querySNMPInterfaces.ts
- src/datasources/entity-ds-react/types.ts
- src/datasources/entity-ds-react/useEntityProperties.ts
- src/lib/client_delegate.ts
- src/lib/function_formatter.ts
HELM-354: Entity DS React updates, get metricFindQuery and template variables mostly working
Will need more work on this, and looking to get feedback, but this PR does the following:
- Get `metricFindQuery` at least mostly working, particularly for Node queries
- Template variable substitution for Node queries
- Handle some attribute mapping
- Added `OnmsColumn` and `OnmsTableData` to make return values more strongly typed
- Add some more typing for return values, etc.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-354
> HELM-354: Entity DS React updates, get metricFindQuery and template variables working

- src/datasources/entity-ds-react/EntityDataSource.ts
- src/datasources/entity-ds-react/EntityHelper.tsx
- src/datasources/entity-ds-react/queries/attributeMappings.ts
- src/lib/client_delegate.ts
Various fixes to React Entity Datasource as per previous PR review suggestions.
- return once at end of `switch/case` statements
- move some helper functions from `EntityDatasource` into `EntityHelpers`
- remove explicit `Promise` statements from `async` functions
- fix `templateSrv.variables` -> `templateSrv.getVariables()` (`.variables` was deprecated), but only in new datasource
- a couple other small fixes
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-354
> HELM-354: Entity DS React fixes as per PR review suggestions

- src/datasources/entity-ds-react/EntityDataSource.ts
- src/datasources/entity-ds-react/queries/queryBuilder.ts
- src/datasources/entity-ds-react/types.ts
Added template variable substitution logic into React Entity Datasource. 
- Moved the logic out of the `EntityDataSource` class itself and into a `queryBuilder` module
- Did some refactoring to reduce the complexity of the `substitution` function
- Added type annotations or made variable names more readable wherever possible
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-354
> HELM-354: Add variable substitution logic for React Entity DS

- docs/modules/installation/pages/debian.adoc
ALEC-267: Remove reference to apt-key in examples - updated the command as per description in ticket for the same issue in ALEC.
At that time, if you have commit …
> ALEC-267: Remove reference to apt-key in examples

- src/components/SwitchBox.tsx
- src/datasources/perf-ds-react/PerformanceAttribute.tsx
- src/datasources/perf-ds-react/PerformanceConfigEditor.tsx
- src/datasources/perf-ds-react/PerformanceDataSource.tsx
- src/datasources/perf-ds-react/PerformanceExpression.tsx
- src/datasources/perf-ds-react/PerformanceFilter.tsx
- src/datasources/perf-ds-react/PerformanceHelpers.ts
- src/datasources/perf-ds-react/PerformanceQueryEditor.tsx
- src/datasources/perf-ds-react/PerformanceStringProperty.tsx
- src/datasources/perf-ds-react/queries/interpolate.ts
- src/datasources/perf-ds-react/queries/queryBuilder.ts
- src/datasources/perf-ds-react/queries/queryStringProperties.ts
- src/datasources/perf-ds-react/types.ts
- src/panels/alarm-table-react/hooks/useAlarmHelmProperties.ts
HELM-331 Convert Performance Datasource to React
Continued work on converting the Performance Datasource to React. This is not complete or fully tested, so it's still a work in progress, but continued work will probably need all/most of this code. You can for example perform attribute queries, including with a node template variable, then apply a filter query such as quantile.
- added Typescript interfaces for many of the data structures
- various fixes to Attribute queries and some work on using template variables
- got Filter queries working
- pulled in and refactored code for String Property queries, not fully tested
- added and refactored variable interpolation code, not fully tested
- added code to convert OpenNMS performance measurement data to Grafana DataFrame format, removed …
> HELM-331: Performance Datasource React conversion work

- src/datasources/perf-ds-react/PerformanceAttribute.tsx
- src/datasources/perf-ds-react/PerformanceDataSource.tsx
- src/datasources/perf-ds-react/PerformanceExpression.tsx
- src/datasources/perf-ds-react/PerformanceFilter.tsx
- src/datasources/perf-ds-react/PerformanceQueryEditor.tsx
- src/datasources/perf-ds-react/constants.ts
- src/datasources/perf-ds-react/queries/interpolate.ts
- src/datasources/perf-ds-react/queries/queryBuilder.ts
- src/datasources/perf-ds-react/types.ts
- fix variable interpolation for node and resource in Attribute queries
- Query Editor, get initial state from existing state (passed in props)
- encapsulate and provide strong typing for API requests
- check whether queries are hidden, filter them out before sending via API
- more comprehensive check for valid Filter queries, don't send to API if invalid
- ensure query targets added or concatenated as arrays to existing query
- various other fixes
* JIRA (Issue Tracker): [http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}](https://opennms.atlassian.net/browse/HELM-331)
> HELM-331: PerfDS React, various query fixes

- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/queries/queryBuilder.ts
- src/datasources/perf-ds/types.ts
- src/lib/utils.ts
Added template variables for performance DS under metricFindQuery
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of …
> Added template variables for performance ds

- package.json
- src/datasources/entity-ds/EntityQueryEditorHelp.tsx
- src/datasources/entity-ds/help-README.md
- src/datasources/entity-ds/module.ts
- src/datasources/flow-ds/FlowQueryEditorHelp.tsx
- src/datasources/flow-ds/help-README.md
- src/datasources/flow-ds/module.ts
- src/datasources/perf-ds/PerformanceQueryEditorHelp.tsx
- src/datasources/perf-ds/help-README.md
- src/datasources/perf-ds/module.ts
- webpack.config.js
- webpack.config.ts
Fix data source help. This PR basically wires things up so that help is displayed for data source help and query editor help. However, it doesn't include any actual contents for the help, this will need to be added.
This is the "?" button next to the data source dropdown in the Query Editor. Grafana looks for a `README.md` in the `datasources/ds-name` directory and displays it. However, our `README.md` were not being copied to the distribution. In addition, our files are more meant for developers to view them on GitHub, not for end users. Added `help-README.md` files which will contain any data source help text, these get copied in the webpack build process.
This is the "(i)" button inside an individual query and is part of the Grafana plugin query editor framework. It can change …
> HELM-302: Datasource and query editor help

- src/datasources/perf-ds/queries/queryBuilder.ts
Fixed issue when working with multiple query types, then hide some to allow better visibility.
As per old plugin Expression, Attribute and Filter queries should allow hidden queries in the payload since they define the transient attribute.
Once the reviewer(s) accept the PR and the …
> Fix issue when hiding mixed query types used in expression

- .circleci/config.yml
We updated our main `webpack.config.ts` to extend the grafana-generated `.config/webpack/webpack.config.ts`, but forgot to update the CircleCI `config.yml`. This is needed (among other things) to make sure the data source help files get included in the final output.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-302
> HELM-302: Fix circleci webpack command to point to main webpack.config.ts

- src/datasources/perf-ds/PerformanceHelpers.ts
- src/datasources/perf-ds/PerformanceQueryEditor.tsx
- src/datasources/perf-ds/PerformanceStringProperty.tsx
- src/datasources/perf-ds/queries/queryStringProperties.ts
- src/datasources/perf-ds/types.ts
fix: to allow stringProperties query to use (single) template variables for node and resources
I'm creating a new PR to allow the use multiple template variables since this would affect all 4 queries (attributes, expressions, string properties and filter)
Once the reviewer(s) accept the …
> Allow stringProperties query to use (single) template variables

- src/components/ClearFilterData.tsx
- src/datasources/entity-ds/EntityConfigEditor.tsx
- src/lib/localStorageService.ts
- src/panels/filter-panel/FilterPanelOptions.tsx
Component to clear Filter Panel data in `localStorage`. This is somewhat of a stopgap in case any selected data is present in `localStorage` after a Filter Panel is removed.
Component added to the Entity Datasource configuration screen as well as to the Filter Panel Options configuration.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-390
> HELM-390: Component to clear Filter Panel data

- src/lib/dashboard-convert/alarmTablePanel.ts
- src/lib/dashboard-convert/convert.ts
- src/lib/dashboard-convert/entityDs.ts
- src/lib/dashboard-convert/filterPanel.ts
- src/lib/dashboard-convert/panels.ts
- src/panels/alarm-table/AlarmTableAlarms.tsx
- src/panels/alarm-table/AlarmTableControl.tsx
- src/panels/alarm-table/AlarmTableData.tsx
- src/panels/alarm-table/AlarmTablePaging.tsx
- src/panels/alarm-table/constants.ts
- src/panels/alarm-table/hooks/useAlarmProperties.ts
Update the Dashboard Conversion tool to convert the Alarm Table Panel.
Also refactors the conversion code to process all panels in a single run.
Not every possible legacy Alarm Table option has been converted, and some do not apply any more since we are relying more on built-in Grafana options, but most significant things have been converted. It is expected that a few more items will need to be done.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-373
> HELM-373: Convert Alarm Table Panel

- src/lib/dashboard-convert/alarmHistogramPanel.ts
- src/lib/dashboard-convert/alarmTablePanel.ts
- src/lib/dashboard-convert/panels.ts
- src/panels/alarm-histogram/constants.ts
Update the Dashboard Conversion tool to convert the Alarm Histogram.
Also fixed this and Alarm Table converter to not override `targets` which are converted in a previous step.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}
> HELM-391: Conversion tool for Alarm Histogram

- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/queries/queryStringProperties.ts
Added support for scopedVars in StringProps query
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) …
> Added support for scopedVars in StringProps query

- src/datasources/perf-ds/PerformanceFilter.tsx
- src/lib/dashboard-convert/performanceDs.ts
Various Performance datasource fixes:
- in Performance Filter query editor, initialize from query props
- in Perf Filter query editor, use `key` instead of `displayName` as `filter` parameter and `filterState` object key
- fix to Attribute Query `fallbackAttribute` conversion
- conversion tool implementation of Performance `stringProperty` query. Needs work but better than previous
Need some more work for String Property conversion. For example the legacy `nodeId` may be in `FS:FI` format, but new React version looking for node id and/or host label; and legacy `resourceId` may not match React version. May need to do API lookups to fill in values correctly. However, at least the user can see the legacy values after dashboard conversion and make updates.
* JIRA (Issue Tracker): …
> Fix Performance DS Filter Query, add StringProperty conversion

- .circleci/config.yml
- .eslintrc
- .eslintrc.json
- docker-compose.yaml
- docs/modules/contributing/pages/developing.adoc
- docs/modules/installation/pages/plugin.adoc
- docs/modules/installation/pages/source.adoc
- makezip.js
- src/debian/rules
- src/lib/utils.ts
- src/plugin.json
This PR changes the plugin to use `opennms-app` for the upstream/official slug, while leaving packaging alone.
Additionally, it adds the schema reference to our `plugin.json` and validates it.
> Update the Grafana Slug + Validate

- src/lib/dashboard-convert/alarmHistogramPanel.ts
- src/lib/dashboard-convert/alarmTablePanel.ts
- src/lib/dashboard-convert/datasources.ts
- src/lib/dashboard-convert/entityDs.ts
- src/lib/dashboard-convert/filterPanel.ts
- src/lib/dashboard-convert/flowHistogramPanel.ts
- src/lib/dashboard-convert/panels.ts
- src/lib/dashboard-convert/utils.ts
Fixes to dashboard conversion code plus some Alarm Table fixes.
- added back `helm` to conversion code that looks for legacy datasources and panels (this had been inadvertently removed)
- force Alarm Table conversion for scrolling to be true (more often that not, horizontal scroll will be needed to display all columns)
- fix Alarm Table number conversion, it's actually `none` instead of `number`
- handle case where legacy datasource has `uid` of a template variable but no `type`
- fix null reference issue
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-408
> HELM-408: Dashboard Conversion and Alarm Table Fixes

- src/panels/alarm-table/AlarmTableAdditional.tsx
- src/panels/alarm-table/AlarmTableControl.tsx
- src/panels/alarm-table/AlarmTableData.tsx
- src/panels/alarm-table/AlarmTableOptions.tsx
- src/panels/alarm-table/AlarmTableTypes.ts
- src/panels/alarm-table/hooks/useAlarmTableMenuActions.ts
Enable a "Use Grafana user" switch for the Alarm Table Panel.
It's set in the Alarm Table Options panel. If set, it will send the username of the currently logged-in Grafana user as the user for alarm ack and other actions. Otherwise, the user is left "unset", in which case the user that is configured in the Entity Datasource will be used.
In Helm 8, the control for this was in the Entity Datasource options; however since we actually call the OpenNMS alarm API from Alarm Table Panel code, I put the "Use Grafana user" switch in the Alarm Table Panel options.
Also as a note, we use the Grafana "Actual user" API which returns info about the current logged-in Grafana user. This includes an `id` which is an integer value assigned by Grafana that has nothing to do with OpenNMS, and a `login` …
> HELM-398: Enable 'Use Grafana user' in Alarm Table Panel

- .circleci/config.yml
Run the `release-lint.sh` script (which checks for `-SNAPSHOT` versions and `npm audit` errors)
> run `release-lint.sh` on `main-*` or tags

- src/datasources/perf-ds/PerformanceFilter.tsx
- src/datasources/perf-ds/queries/queryBuilder.ts
fix: resolve the error in performance Filter datasource
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green …
> HELM-406: Adding a perf filter query to a dashboard elicits "TypeError: l is undefined"

- src/datasources/entity-ds/EntityClause.tsx
fix: issue when creating a query, then saving the query and reopen in edit mode it resets equality to default EQ.
Now should work accordingly setting the equality to the corresponding from the original query.
Once the reviewer(s) accept the PR and the branch passes continuous integration …
> HELM-411: Alarm datasource query not keeping proper equality

- src/datasources/perf-ds/queries/queryStringProperties.ts
Grafana reviewer reported this. Grafana `TemplateSrv.replace` calls `string.replace` on the `target` variable, expecting it to be a string, but we were passing `nodeId` as a `number`. Coerced it to a string.
* JIRA (Issue Tracker): [http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}](https://opennms.atlassian.net/browse/HELM-421)
> HELM-421: Fix, nodeId passed to templateSrv.replace must be a string

- src/datasources/entity-ds/EntityDataSource.ts
- src/datasources/entity-ds/types.ts
- src/lib/localStorageService.ts
- src/panels/filter-panel/FilterPanelControl.tsx
- src/panels/filter-panel/FilterPanelOptions.tsx
- src/panels/filter-panel/FilterPanelTypes.ts
Tie local storage for Filter Panels to the dashboard they are on. Entity Datasource will load proper filter settings for the dashboard it's being called by. This allows multiple dashboards with their own Filter Panel to work simultaneously.
May need a little more runtime testing but is generally working.
Also, ideally local storage for a dashboard would be removed when a dashboard is deleted, was unable to find a hook for doing this. User can always clear all Filter Panel local storage data from buttons within Filter Panel Options or Entity Datasource configuration.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-389
> HELM-389: Filter Panel, tie to dashboard

- src/datasources/perf-ds/PerformanceAttribute.tsx
- src/datasources/perf-ds/PerformanceQueryEditor.tsx
- src/datasources/perf-ds/queries/queryBuilder.ts
When using the Performance data source and Attribute query, if user changed the node in the query editor dropdown, the resource data was not being updated, so the query retained the previous node information.
This PR makes an update to re-query and repopulate the resources for the new node. In some cases, the previously-selected resource is not applicable to the newly selected node, in which cases resources are cleared.
This works when selecting a node from the query editor as well as if a template variable was used for the node and user changes the template variable from the dashboard dropdown.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-417
> HELM-417: Performance query hardcoding node id

- src/datasources/perf-ds/PerformanceAttribute.tsx
- src/datasources/perf-ds/queries/queryBuilder.ts
HELM-425: Fix logic for sending `transient: true` in Performance data source Measurement API queries. Should only be sent when a query has been flagged as `hidden`.
Previous logic resulted in `transient: true` almost always being sent, resulting in `204: No Content` responses, making it appear that Performance data source was not working at all.
HELM-424: Fix some issues which caused user to not be able to select a node from the Node dropdown in a Performance query.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-424,
* https://opennms.atlassian.net/browse/HELM-425
> HELM-424, HELM-425: Fix transient flag logic in Perf DS queries, node selection

- src/lib/dashboard-convert/convert.ts
- src/lib/dashboard-convert/performanceDs.ts
- src/lib/dashboard-convert/requires.ts
Fix Performance data source converter to move Attribute `label` correctly. This was causing Performance queries with Expressions to fail after conversion.
Also adds data source conversion for `__requires` section.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-414
> HELM-414: Fix PerfDS label conversion, add 'requires' conversion

- src/dashboards/cortex_flow_deep_dive.json
- src/dashboards/flow_deep_dive.json
Importing the included dashboards via "Configuration > Plugins > Dashboards" was failing.
Fix includes:
- setting dashboard `id` to null, looks like this is needed to import correctly
- removing `uid`
- `version` needs to be same or 1 more than previous value. Grafana does a check if version is mismatched, thinking it means "someone else" updated it. It could be that having a gap in version triggers this error.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-422
> HELM-422: Fix Dashboard Import for included dashboards

- src/dashboards/cortex_flow_deep_dive.json
- src/lib/dashboard-convert/graphToTimeSeriesPanel.ts
Convert the Cortex Flow Deep Dive dashboard to be compatible with OPG v9.
Also a small update to the dashboard convert code.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-422
> HELM-422: Convert Cortex Flow dashboard

- site.yml
Fixes a couple issues preventing the Antora site documentation from building.
There was a syntax error (missing colon after `destinations`) and also need to use `release-9.x` branch as the content source instead of `tag: v*`. Antora saw `v*` tag and tried to get files from GitHub repo tag v4.0.1.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-443
> HELM-443: Fix antora content source to fix documentation build

- src/datasources/entity-ds/EntityClause.tsx
- src/datasources/entity-ds/EntityDataSource.ts
- src/datasources/entity-ds/queries/queryBuilder.ts
- src/lib/dashboard-convert/entityDs.ts
Fixed some issues with Entity data source date and multi-value handling, which were causing behavior in the bug ticket.
- use either `comparedString` or `comparedValue` in query clauses, but not both. This was causing some mixups with how queries were sent to the Rest API
- using `datetime-local` input type for dates, allows user to set the full date and time and uses ISO date format when sending to Rest API
- remove any empty query clauses before sending to `opennms-js` and doing the Rest query. This could happen when a mult-value template variable is used but all options are deselected, and was causing an invalid query to be sent. Behavior now is as if the filter was not applied at all
- also fixes HELM-442 issue entering manual text (like a template variable) in an Entity DS `where` …
> HELM-440: Fix date and multi-value handling in Entity clauses and queries

- src/datasources/perf-ds/PerformanceFilter.tsx
Performance Filter parameters and defaults are being converted correctly, however the filter query editor was not using the defaults if a specific value did not exist; this fixes that, see `paramValueOrDefault`.
Also reformatted the file to have 2 space indentation (current standard).
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-441
> HELM-441: Use Perf Filter default param if available

- src/datasources/perf-ds/PerformanceHelpers.ts
- src/datasources/perf-ds/types.ts
Convert any 'NaN' values received by the Performance data source to nulls. This was done in v8 of this plugin.
Was causing issues with for example the Stat Grafana visualization panel using the Calculation "Last *", which displays the last non-null value, however it would consider `"NaN"` to be a valid value and display it instead of a valid numeric value.
Flows has the `nanToZero` feature which may be more appropriate for flows data.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-446
> HELM-446: Convert Perf datasource NaN values to nulls

- src/datasources/perf-ds/PerformanceHelpers.ts
- src/datasources/perf-ds/queries/interpolate.ts
- src/test/react/lib_utils.spec.ts
- src/test/react/perf_ds_interpolate.spec.ts
Allow `$var`, `${var}` and `${var:fmt}` syntax in template variable references in Performance data source queries.
Note that we don't do any special format processing when a format is specified.
Also did some refactoring of the interpolation code.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-430
> HELM-430: Performance datasource, allow brace and brace:fmt variable syntax

- src/datasources/entity-ds/types.ts
- src/panels/filter-panel/FilterPanelControl.tsx
- src/panels/filter-panel/FilterPanelControlField.tsx
- src/panels/filter-panel/FilterPanelLayoutOptions.tsx
- src/panels/filter-panel/FilterPanelOptions.tsx
- src/panels/filter-panel/FilterPanelTypes.ts
Add a Horizontal layout option to the Filter Panel.
The v8 Filter Panel had a horizontal layout, i.e. all items in a single, wrapping row. v9 by default has a vertical layout, each item label/value is on its own row, which is generally more readable. However there may be situations in which users prefer a horizontal layout.
Note also that the vertical layout does scroll vertically so all items can be accessed (the initial issue in HELM-439).
Code for the fields themselves was refactored into `FilterPanelControlField.tsx` to allow reuse.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-439
> HELM-439: Filter Panel horizontal layout option

- src/lib/dashboard-convert/datasources.ts
- src/lib/dashboard-convert/inputs.ts
- src/lib/dashboard-convert/panels.ts
- src/lib/dashboard-convert/templating.ts
- src/lib/dashboard-convert/utils.ts
HELM-438: Dashboard converter retains original datasource name/label/uid when possible
Dashboard converter tool will retain the original datasource name and label if present, and if the datasource uid reference is a template or input variable, it will retain it instead of using the uid of the installed v9 datasource.
This will help in cases where multiple instances of an OpenNMS datasource are used, for example if they point to different OpenNMS instances.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-438
> HELM-438: Dashboard converter retains original datasource name/label/uid

- src/datasources/entity-ds/EntityClause.tsx
- src/datasources/entity-ds/EntityClauseEditor.tsx
- src/datasources/entity-ds/EntityQueryEditor.tsx
- src/datasources/entity-ds/queries/queryIPInterfaces.ts
- src/test/react/flow_ds_datasource.spec.ts
Include the node ID in IP interface Entity Datasource query results. Note that node label is not in the underlying Rest API and was not previously available in Helm v8.
Also fixed a few other issues:
- changed clause value input type to 'text' instead of 'number', even if value is a number. This was preventing users from using a template variable in this field
- fixed some issues with comparator handling which was preventing clauses from being converted to filters and sent in the Rest API call
- flow unit test
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/OPG-461
> OPG-461: Include nodeid in ipinterface query results

- src/lib/dashboard-convert/performanceDs.ts
Dashboard converter was outputting an extra right bracket `]` in `stringPropertyState.resource.id`.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/OPG-448
> OPG-448: Dashboard converter was outputting extra bracket

- src/datasources/flow-ds/helpers.ts
- src/lib/utils.ts
Allow 'withHost' Flows queries with multi-valued parameters for the 'host' value.
Needed to convert the `withHost` parameter from a string to an array, e.g. from `withHost: '{host1,host2}'` to `withHost: ['host1', 'host2']`
This was causing `opennms-js` Rest API call to be:
```
http://localhost:3000/api/datasources/proxy/uid/some-id/rest/flows/hosts/series?start=1694178697745&end=1694200297745&step=30989&host={0.0.0.0,0.0.0.1}
```
instead of
```
http://localhost:3000/api/datasources/proxy/uid/some-id/rest/flows/hosts/series?start=1694178697745&end=1694200297745&step=30989&host=0.0.0.0&host=0.0.0.1
```
Also fixed another issue getting interfaces if nodes was a multi-valued variable.
There are other places where we may not handle multi-valued variables correctly, may refactor a bit as we …
> OPG-454: Allow Flows query with multi-valued withHost

- docs/antora.yml
- package-lock.json
- package.json
- site.yml
- src/datasources/entity-ds/queries/queryIPInterfaces.ts
- src/datasources/entity-ds/queries/querySNMPInterfaces.ts
- src/plugin.json
Part of OPG-464:
- add `nodeId` to Entity data source SnmpInterfaces query
- node `nodeId` column for IP Interfaces query results
There are more issues in OPG-464 but they require changes to both OpenNMS/Horizon as well as `opennms-js` first.
Update: removed adding `ipInterfaceId` to Monitored Services query results, needs to be added to `opennms-js` first. Also bumped snapshot to 9.0.10.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-464
> OPG-464: Add nodeID to EntityDS SnmpInterfaces queries, IP nodeId column placement

- src/panels/alarm-table/AlarmTableAdditional.tsx
- src/panels/alarm-table/AlarmTableControl.tsx
- src/panels/alarm-table/AlarmTableTypes.ts
- src/panels/alarm-table/hooks/useAlarmTableMenuActions.ts
Adds an option to auto-refresh the Alarm Panel after performing an action such as `acknowledge`, `clear` or `escalate` on one or more alarms, so the user sees realtime updated data after performing the action (e.g. `Ack` field displays "true" instead of "false" after an `Acknowledge`).
The Grafana runtime does not appear to offer a way to refresh a panel or the dashboard programmatically, so here we "click" the "Refresh dashboard" button. Note, there could be issues if Grafana changes or removes this button in a future version (the `RefreshPicker` component).
Grafana React appears to have removed `getTimeSrv()` or any other access to the `TimeSrv` service, which includes `refreshTimeModel()` which could be used to refresh the query and panel. See …
> OPG-470: Alarm Panel auto refresh after action

- src/panels/alarm-table/AlarmTableAdditional.tsx
- src/panels/alarm-table/AlarmTableColumnSizes.tsx
- src/panels/alarm-table/AlarmTableOptions.tsx
- src/panels/alarm-table/AlarmTableTypes.ts
- src/panels/alarm-table/hooks/useAlarmProperties.ts
Allow option to have custom column widths for the Alarm Table panel.
Grafana takes care of sizing the column widths for panels using the `Table` component, which we use in the Alarm Table, and doesn't seem to provide a way to retain or access those widths. If a user resizes a panel, Grafana will auto-size the column widths again. If that is not desired, then this option can be used.
Adds a new "Column Sizes" section to the panel options editor. User can enable/disable, add columns and set widths, in pixels, click on the red icon to delete.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-469
> OPG-469: Alarm Table panel custom column widths

- src/datasources/entity-ds/EntityDataSource.ts
- src/datasources/entity-ds/EntityHelper.tsx
- src/datasources/entity-ds/constants.ts
- src/datasources/entity-ds/types.ts
- src/lib/function_formatter.ts
- src/lib/utils.ts
First part of OPG-468.
Allows specifying a `labelFormat` and `valueFormat` for the Entity data source `nodeFilter()` query.
Can be one of ['id', 'label', 'id:label', 'label:id', 'fs:fid'] for either of these.
`labelFormat` is the format for display, for example in a template variable dropdown list or in the Preview of values.
`valueFormat` is the format of the value used to interpolate variables, send to the server, etc.
Additional attributes can be specified, as before, including template variables.
For example, specifying the template variable query
```javascript
nodeFilter(labelFormat=label,valueFormat=id,location=$location)
```
would filter nodes by the location specified in the template variable `$location`, display the node label and use the node id in a query.
This also includes a …
> OPG-468: Add labelFormat and valueFormat to EntityDS nodeFilter

- src/constants/constants.ts
- src/datasources/entity-ds/EntityDataSource.ts
- src/datasources/entity-ds/EntityHelper.tsx
- src/datasources/entity-ds/types.ts
- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/PerformanceHelpers.ts
- src/hooks/useEntities.tsx
- src/lib/function_formatter.ts
- src/panels/filter-panel/FilterPanelControl.tsx
- src/test/react/function_formatter.spec.ts
Refactored `function_formatter.ts` into individual functions vs. static methods in a class, this is much more "Typescript-y". Also can import just the functions you need to use. Fixed formatting, etc.
Moved `parseFunctionInfo` there since it will be reused by the Performance data source.
Also added `fs:label` specifier for both label and value.
Next PR will be to add `labelFormat` and `valueFormat` to the Performance data source `nodeFilter` query.
Refactored the `format_formatter.spec.ts` test to use `test.each` to remove a bunch of code duplication. Fix various Sonar issues. Marked one regex as `// NOSONAR` as it's not trivial to fix and has been in production for years.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-468
* Continuous Integration: …
> OPG-468: Refactor FunctionFormatter into individual functions

- src/datasources/entity-ds/EntityDataSource.ts
- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/PerformanceQueryEditor.tsx
- src/lib/function_formatter.ts
Add `labelFormat` and `valueFormat` to the Performance data source `nodeFilter()` query.
Refactored some functions into `function_formatter.ts` and fixed a function name typo.
See PR #937 for more info.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-468
> OPG-468: Add labelFormat, valueFormat to PerfDS nodeFilter

- src/datasources/entity-ds/queries/queryBuilder.ts
- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/types.ts
If a template variable is used in an Entity query, and the template variable specifies a `text` format specifier, e.g. `${node:text}`, make sure to use that `text` value rather than the `value` value for creating the query clause, for both single-valued and multi-valued template variables.
Example: you define a template variable `node` using a Performance datasource, `nodeFilter()` query, with `Multi-value` turned on. This will result (after PerfDS `metricFindQuery`) in the templateVariable `current` field (a `@grafana/data VariableOption` object) to have the node `label` in the `text` value array and node `fs:fid` in the `value` value array.
Then in say an Alarm Table panel, you define an Entity query on Alarms with a clause that the `Node: Label` equals `${node:text}`. This should …
> OPG-466: Allow template variable text format substitution when used in Entity queries

- src/panels/alarm-table/hooks/useAlarmProperties.ts
Fixed a bug in the Alarm Panel when calculating which rows of data to display for the given page.
Looks like we assumed `field.values` was always an `ArrayVector` having a `buffer` array field which we were accessing directly, however `field.values` is a `Vector` and might only contain `length` and `toArray()` fields. Using `toArray()` instead, and also cleaning up some code (use `slice()` instead of `splice()`, etc.).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-473
> OPG-473: Fix Alarm Panel bug when calculating page rows

- package.json
- src/panels/alarm-table/AlarmTableAdditional.tsx
- src/panels/alarm-table/AlarmTableControl.tsx
- src/panels/alarm-table/AlarmTableTypes.ts
- src/panels/alarm-table/hooks/useAlarmTableMenuActions.ts
Display a message after an Alarm Table menu action, such as `acknowledge`, `clear` or `escalate`.
Previously in #930 we "clicked" the Dashboard Refresh button to auto-refresh the Alarm Panel after performing an action, to display the current state. However, Grafana strongly discourages programmatically re-querying or refreshing (in fact, disallowed our change).
In this PR, a "toast" success or error message will appear after user performs an action; the `success` message notifies that user will need to manually refresh the panel to get the current alarm status.
Displaying the message is configurable in the panel Options editor; it's enabled by default.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-474
* Continuous Integration: …
> OPG-474: Display message after Alarm Table action

- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/lib/function_formatter.ts
Fixes a bug in `nodeResources()` (Performance data source), arguments were not being split correctly.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-475
> OPG-475: Fix nodeResources() arguments

- docs/modules/datasources/pages/performance_datasource.adoc
- src/components/ValueOverrideSwitch.tsx
- src/datasources/perf-ds/InputValueOverrideConfig.tsx
- src/datasources/perf-ds/PerformanceAttribute.tsx
- src/datasources/perf-ds/PerformanceConfigEditor.tsx
- src/datasources/perf-ds/PerformanceDataSource.tsx
- src/datasources/perf-ds/PerformanceQueryEditor.tsx
- src/datasources/perf-ds/types.ts
OPG-477: Updates to Enable Input Value Override Components implementation, naming and documentation
Makes Grafana-recommended fixes (`InlineSwitch` instead of `Switch`) as well as naming and documentation fixes for this feature.
This feature is an optional features, disabled by default, which allows a user to manually enter text input for some fields in a Performance Datasource query builder.
Usually values for nodes, attributes, resources, etc. display in a dropdown selection control, and some will also accept text input (e.g. a template variable or expression), but in some cases that kind of manual text input isn't accepted, for example due to validation on that input field. We've made improvements so that usually it **is** accepted, and also that for example template variables now …
> OPG-477: Updates to Enable Input Value Override Components

- src/datasources/perf-ds/PerformanceAttribute.tsx
Fix the initialization of resource template variable in Performance Attribute queries.
If user had entered a template variable in the Resource input, it was being saved, but then upon returning to the edit screen it was being reset to empty, having the effect of not retaining its value.
This fix does a check if a template variable was used and doesn't reset the value.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/OPG-483
> OPG-483: Fix initialization of resource variable in PerformanceAttribute

- .circleci/config.yml
- src/datasources/perf-ds/queries/queryBuilder.ts
- src/datasources/perf-ds/types.ts
- src/lib/dashboard-convert/performanceDs.ts
[NMS-16582](https://opennms.atlassian.net/browse/NMS-16582) may be caused by the fact that `subAttribute` and `datsource` are not correctly mapped in OPG v9 for Performance queries.
This fixes the mapping from the OPG query builder UI (`Sub-Attribute`) and also changes the name from `subAttribute` to `datasource` for the query to OpenNMS Measurements Rest API. It also fixes the dashboard converter to map it correctly.
Additionally, we use a Python script `check_jsonschema` to validate our `src/plugins.json` file during the Circle CI build process. The schema file we use has some Python-regex specific formulations like `\\-` and `\\%`. Needed to add `--regex-variant python` to account for this; apparently the default is not to use those Python-specific regex elements.
* JIRA (Issue …
> OPG-493: Fix mapping of subAttribute and datasource in Perf DS

- README.md
Making sure this is in v9.
Should be: https://cortexmetrics.io/
> Fix link for Cortex - in release-9.x

- src/datasources/perf-ds/PerformanceAttribute.tsx
Description:
This pull request fixes a TypeError that occurred when processing data from the Performance data source. The previous code was attempting to access a property on an undefined variable, which would cause the plugin to fail.
The fix ensures the variable is correctly checked for a value before being used, preventing the error. 
Release-9.x 
Please Review:
@synqotik
@marshallmassengill
> Fix: Handle undefined value in performance attribute Jira-OPG-492
