src/panels/alarm-table/alarm_details.html
src/panels/alarm-table/alarm_details.js
src/panels/alarm-table/module.js
src/panels/alarm-table/renderer.js
src/panels/alarm-table/transformers.js

JIRA: https://issues.opennms.org/browse/HZN-1099

HZN-1099: Add a modal dialog with additional alarm details.

---

src/datasources/fault-ds/query-directive.js

* JIRA: https://issues.opennms.org/browse/HELM-21

HELM-21: Update target filter definition when deleting an element

---

src/datasources/fault-ds/FilterCloner.js
src/datasources/fault-ds/client_delegate.js
src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/mapping/ValueMapping.js
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-18

HELM-18: Add support for using template variables as query parameters

---

dist/datasources/fault-ds/client_delegate.js
package.json
src/datasources/fault-ds/client_delegate.js
src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/mapping/ValueMapping.js
src/datasources/fault-ds/query-directive.js
yarn.lock

In order to get this to work, the following PRs must be merged before:
* https://github.com/OpenNMS/opennms/pull/1616
In order to test this, the following steps need to be done:
* Check out this branch and compile it
* Manually build opennms from the branch above and start it.
JIRA: https://issues.opennms.org/browse/HELM-22

HELM-22: Use actual comparators and properties instead of hard-coding them

---

src/datasources/fault-ds/client_delegate.js
src/datasources/fault-ds/datasource.js

* JIRA: https://issues.opennms.org/browse/HELM-16

HELM-16: Allow users to escalate/clear alarms

---

src/datasources/fault-ds/datasource.js
src/panels/alarm-table/alarm_details.html
src/panels/alarm-table/alarm_details.js
src/panels/alarm-table/memo_editor.js
src/panels/alarm-table/module.js

JIRA: https://issues.opennms.org/browse/HELM-20

HELM-20: Refresh the dashboard after taking action on alarms.

---

src/datasources/fault-ds/query-directive.js
src/datasources/fault-ds/ui/Query.js
src/datasources/fault-ds/ui/Restriction.js
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-25

HELM-25: Only consider fully defined restrictions

---

src/datasources/fault-ds/query-directive.js
src/datasources/fault-ds/ui/Restriction.js

* JIRA: https://issues.opennms.org/browse/HELM-24

HELM-24: Handle comparators on type change accordingly

---

src/datasources/fault-ds/datasource.js
src/panels/alarm-table/renderer.js

* JIRA: https://issues.opennms.org/browse/HELM-17
Depends on https://github.com/OpenNMS/opennms/pull/1631 and https://github.com/OpenNMS/opennms-js/pull/13

HELM-17: Show ticket operations according to ticketer config/ticket state

---

src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/partials/query.options.html
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-12

HELM-12: Add from and  to template variables

---

src/datasources/fault-ds/ui/Clause.js

* JIRA: https://issues.opennms.org/browse/HELM-23

HELM-23: Do not re-initialize segment for condition if already defined

---

src/datasources/fault-ds/mapping/ValueMapping.js

* JIRA: https://issues.opennms.org/browse/HELM-35
Must be merged after PR https://github.com/OpenNMS/opennms-js/pull/14

HELM-35: Defer null value handling to opennms.js client

---

src/datasources/fault-ds/datasource.js
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-27

HELM-27: Always limit alarms to match lastEventTime >= $range_from AND lastEventTime <= $range_to

---

src/datasources/fault-ds/query-directive.js
src/datasources/fault-ds/ui/Query.js

* JIRA: https://issues.opennms.org/browse/HELM-36

HELM-36: invoke updateTargetfilter only once

---

src/datasources/fault-ds/client_delegate.js
src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/partials/config.html
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-19

HELM-19: Add option to use the grafana login, name or email instead of the datasource name

---

src/panels/alarm-table/renderer.js

Must be merged after https://github.com/OpenNMS/grafana-opennms-helm-app/pull/23 (HELM-19)
* JIRA: https://issues.opennms.org/browse/HELM-15

HELM-15: Allow users to acknowledge and un-acknowledge alarm from the alarm table panel

---

src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/query_ctrl.js
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-33

HELM-33: Fix de-serialization issue with target filter

---

src/datasources/fault-ds/datasource.js

* JIRA: https://issues.opennms.org/browse/HELM-26
Missing attributes are `Event Label` and `Ticket URL`, but they are not yet exposed via the rest endpoints.

HELM-26: Flatten all alarm parameters

---

src/datasources/fault-ds/client_delegate.js

* JIRA: https://issues.opennms.org/browse/HELM-41

HELM-41: Reset clientWithMetadata on error

---

src/datasources/fault-ds/Examples.js
src/datasources/fault-ds/module.js
src/datasources/fault-ds/partials/query.options.html

* JIRA: https://issues.opennms.org/browse/HELM-43

HELM-43: Provide examples and allow users to create new query from any example

---

src/datasources/fault-ds/client_delegate.js
src/datasources/fault-ds/datasource.js
src/spec/fault_ds_datasource_spec.js

* JIRA: https://issues.opennms.org/browse/HELM-42

HELM-42: Enforce Alarm ReST API v2

---

src/datasources/fault-ds/datasource.js
src/datasources/fault-ds/mapping/AttributeMapping.js
src/datasources/fault-ds/partials/query.editor.html
src/datasources/fault-ds/query-directive.js
src/datasources/fault-ds/query_ctrl.js

* JIRA: https://issues.opennms.org/browse/HELM-45

HELM-45: Allow users to toggle between all or featured attributes

---

docs/getting_started/basic_walkthrough.adoc
src/datasources/fault-ds/plugin.json
src/datasources/perf-ds/plugin.json

JIRA: https://issues.opennms.org/browse/HELM-48

HELM-48: Rename data sources for clarity.

---

src/datasources/fault-ds/mapping/FilterMapping.js

* JIRA: https://issues.opennms.org/browse/HELM-50

HELM-50: Properly initialize parentQuery for all nested clauses

---

src/datasources/fault-ds/datasource.js

Depends on https://github.com/OpenNMS/opennms-js/pull/18

HELM-13: Expose the event label and locations.

---

src/panels/alarm-table/alarm_details.html

* JIRA: https://issues.opennms.org/browse/HELM-31
Depends on https://github.com/OpenNMS/opennms-js/pull/19

HELM-31: Properly display ticket information

---

src/panels/alarm-table/alarm_details.html
src/panels/alarm-table/module.js

JIRA: https://issues.opennms.org/browse/HELM-70

HELM-70: Scroll!

---

src/dashboards/flow_deep_dive.json
src/plugin.json

JIRA: https://issues.opennms.org/browse/HELM-93

HELM-93: Include the flow deep dive dashboard as part of the plugin.

---

docs/_topic_map.yml
docs/datasources/flow_datasource.adoc
src/datasources/flow-ds/datasource.js
src/lib/client_delegate.js

JIRA: https://issues.opennms.org/browse/HELM-96

HELM-96: Document the flow datasource.

---

src/datasources/fault-ds/datasource.js

This PR adds 'isSituation' as a featured value for filtering the datasource and provides handling to set choice values to 'true' and 'false'
Depends on PR https://github.com/OpenNMS/opennms/pull/2058 to add required functionality functionality to the OpenNMS REST API.
* JIRA: https://issues.opennms.org/browse/HZN-1350

HZN-1350: Filter Alarms on isSituation

---

package.json
src/datasources/fault-ds/datasource.js
src/panels/alarm-table/alarm_details.html
src/panels/alarm-table/alarm_details.js
yarn.lock

This PR allows the helm Alrm tables to be built : 
* filtering on whether an Alarm is in a situation or not
* by the number of nodes the alarm or situation affects (affectedNodeCount) and 
* by the number of correlated alarms in the situation (situationAlarmCount).
The latter 2 are displayable as columns.

OCE - ReST updates

---

README.md
src/panels/alarm-table/editor.html
src/panels/alarm-table/editor.js
src/panels/alarm-table/sass/table.scss

Add support for reordering columns in the alarm table config.

HELM-63: allow reordering of elements

---

src/datasources/fault-ds/datasource.js

This PR fixes a simple fat finger typo which places the incorrect spelling of the attribute in the drop down for table configuration.

HZN-1396: Fix typo in FeaturedAttirbute

---

src/panels/alarm-table/editor.js

* JIRA: https://issues.opennms.org/browse/HELM-123
This seems to fix drag&drop reordering in IE 11 and Firefox 63, while still working in Chrome.
(There seemed to be quite a few different ways to get the same element, however, so I'm not sure if this is the appropriate way. Feel free to change / improve it before merging.)

HELM-123: make drag&drop work in IE and Firefox

---

src/datasources/perf-ds/datasource.js
src/datasources/perf-ds/query_ctrl.js
src/spec/perf_ds_datasource_spec.js

https://issues.opennms.org/browse/NMS-8942

NMS-8942: Preserve order in queries

---

src/datasources/perf-ds/datasource.js
src/datasources/perf-ds/query_ctrl.js
src/spec/perf_ds_datasource_spec.js

Reverts OpenNMS/opennms-helm#81
These changes don't work with template variables.

Revert "NMS-8942: Preserve order in queries"

---

docs/_topic_map.yml
docs/datasources/performance_datasource.adoc

This isn't exhaustive, but it's a start...

Initial documentation for the performance datasource.

---

src/datasources/fault-ds/datasource.js
src/panels/alarm-table/column_options.js
src/panels/alarm-table/module.js
src/panels/alarm-table/renderer.js
src/panels/alarm-table/sass/table.scss

* add `Is Acknowledged` to the data returned by the fault-ds
* add a new `Boolean` column type to the Alarm Table panel which
can display Y/N/true/false/etc. as a checkbox or not

HELM-135: `isAcknowledged` enhancements

---

package.json
src/panels/alarm-table/module.html
src/panels/alarm-table/module.js
src/panels/alarm-table/sass/_table.scss
yarn.lock

It should not have been this easy.  :D
JIRA: https://issues.opennms.org/browse/HELM-159

HELM-159: add CSV and Excel export

---

README.md
package.json
src/panels/alarm-table/module.js
src/panels/alarm-table/renderer.js
webpack.config.js
yarn.lock

After working with @pbrane, we've changed the default alarm table columns and formatting.
Before:
After:
This PR also includes some fixes for issues I ran into with the differences between `@grafana/ui` and `@grafana/data` in 6.0 through 6.3 grafana releases.  I opted to leave `@grafana/ui` alone (since the bits we're still importing there are part of the public interface) but including `@grafana/data` bits (introduced in 6.2 and/or 6.3) and compiling them in as part of webpack rather than assuming they're there at runtime.
One or more …

HELM-172: new alarm table defaults

---

package.json
yarn.lock

build(deps-dev): bump babel to 7.6

---

package.json
src/panels/alarm-table/editor.html
src/panels/alarm-table/renderer.js
src/panels/alarm-table/sass/_table.scss
yarn.lock

HELM-181: use fontawesome instead of ionicons, fix outlines

---

.gitignore
.vscode/settings.json
DEVELOPMENT.md
src/datasources/entity-ds/Mapping.js
src/datasources/entity-ds/UI.js
src/datasources/entity-ds/constants.js
src/datasources/entity-ds/mapping/FilterMapping.js
src/datasources/entity-ds/mapping/OrderByMapping.js
src/datasources/entity-ds/partials/query.editor.html
src/datasources/entity-ds/partials/query.html
src/datasources/entity-ds/query-directive.js
src/datasources/entity-ds/query_ctrl.js
src/datasources/entity-ds/ui/Controls.js
src/datasources/entity-ds/ui/Filter.js
src/datasources/entity-ds/ui/OrderBy.js
src/datasources/entity-ds/ui/Query.js
src/panels/alarm-table/editor.js
src/panels/alarm-table/module.js
webpack.config.js

This PR adds support for "order by" in the entity datasource.  It also includes a few minor build/project changes I wanted while working on the code.
A tooltip was added to make it clear that this is independent of the sorting done in the columns of the alarm table, it's only to affect which data gets pulled when limits are used.
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, …

HELM-174: add "orderBy" support to the entities query page

---

src/panels/alarm-histogram/ctrl.js
src/panels/alarm-table/alarm_details.html
src/panels/filter-panel/ctrl.js
src/panels/flow-histogram/ctrl.js

JIRA: https://issues.opennms.org/browse/HELM-183

HELM-183: Fix custom panel rendering to PNG

---

src/datasources/flow-ds/add_opennms_func.js
src/datasources/flow-ds/css/query-editor.css
src/datasources/flow-ds/flow_functions.js
src/datasources/flow-ds/func_editor.js

HELM-192: improve layout of function controls

---

src/panels/alarm-table/table_model.js
src/spec/alarm_table_model_spec.js

JIRA: https://issues.opennms.org/browse/HELM-202

HELM-202: Sort meta-data along with rows

---

package-lock.json
package.json
src/lib/grafana_resource.js
src/panels/alarm-table/column_options.js
src/panels/alarm-table/renderer.js
src/plugin.json
webpack.config.js

This PR fixes issues rendering the alarm table.
Grafana has been moving things around between `@grafana/ui` and `@grafana/data`.  This patch updates Helm to find the methods we need at runtime.
Unfortunately this means the minimum Grafana version is now 6.3, rather than 6.0, so I'm making this patch against develop (Helm 5) rather than the `4.0.x` branch.  Looks like we should retarget 4.0.3 to 5.0.0 to be compliant with `semver`.
If you know that a particular person is subject matter …

HELM-196: fix issues with @grafana/ui and @grafana/data loading in 6.5.x

---

package-lock.json
package.json
src/lib/grafana_resource.js
src/panels/alarm-table/column_options.html
src/panels/alarm-table/column_options.js
src/panels/alarm-table/editor.html
src/panels/alarm-table/module.js
src/panels/alarm-table/renderer.js
src/panels/alarm-table/transformers.js
src/plugin.json
webpack.config.js

This PR merges most of the latest changes from the Grafana 6.6 `table` plugin.  It fixes rendering issues with numeric columns in Grafana 6.6.
This PR depends on [HELM-196](https://github.com/OpenNMS/opennms-helm/pull/263) being merged first.
Once the reviewer(s) accept the PR and the …

HELM-212: fix column rendering issues

---

.circleci/config.yml

Migrated the current workflow from CircleCI 2.0 to CircleCI 2.1.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-219

HELM-219: Migrate CircleCI 2.0 to 2.1

---

src/datasources/perf-ds/query_ctrl.js

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-208
* Continuous Integration: [Bamboo](https://bamboo.opennms.org/), [CircleCI](https://circleci.com/gh/OpenNMS/opennms-js)

HELM-208: don't throw an error when the user is first configuring a filter

---

docs/modules/installation/pages/requirements.adoc

HELM-251: Updated  Grafana server requirements to 6.3 throuh 6.7
* [x ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [ x] Have you made a comment in that issue which points back to this PR?
* [ x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create …

HELM-251: Update Grafana server requirements

---

.circleci/config.yml
src/datasources/flow-ds/datasource.js
src/lib/utils.js

Quick fix to Helm to handle different forms of `intervalToMs`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-261

HELM-261: thunking for intervalToMs

---

.circleci/config.yml
docs/modules/datasources/pages/performance_datasource.adoc
docs/modules/installation/pages/debian.adoc
docs/modules/installation/pages/plugin.adoc
docs/modules/installation/pages/rpm.adoc

1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: the subject of pull request`
I have added a local Antora build run that produces a static HTML site.zip as an artifact just with the content from the specific branch. It should give a developer and reviewer quicker feedback for validation. Added also an Xref validation step which blames when cross-references can't be resolved correctly.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-268

HELM-268: Add Xref validation to HELM CI/CD

---

src/lib/client_delegate.js

The issue was originally created for `NMS` but later on it was decided to improve the situation in `HELM`.
Issue: https://issues.opennms.org/browse/NMS-13114

NMS-13114: improve error message in case of a "too many buckets" exception

---

docs/modules/datasources/pages/flow_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc
docs/modules/panel_configuration/pages/dynamic-dashboard.adoc

updated broken links.
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the …

NMS-12497: migrate docs to antora

---

src/dashboards/flow_deep_dive.json

* JIRA (Issue Tracker): https://issues.opennms.org/projects/HELM/issues/HELM-277

HELM-277: flow dashboard update for Grafana 7

---

docs/modules/ROOT/nav.adoc
docs/modules/getting_started/pages/index.adoc
docs/modules/installation/pages/db-reports.adoc
docs/modules/installation/pages/debian.adoc
docs/modules/installation/pages/plugin.adoc
docs/modules/installation/pages/rpm.adoc
docs/modules/reference/pages/how-to-build-with-docker.adoc

HELM 265: cannot use grafana-image-renderer with Helm's docker image

---

docs/modules/datasources/pages/entity_datasource.adoc
docs/modules/datasources/pages/flow_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc
docs/modules/getting_started/pages/basic_walkthrough.adoc
docs/modules/getting_started/pages/importing.adoc
docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
docs/modules/installation/pages/debian.adoc
docs/modules/installation/pages/upgrading.adoc
docs/modules/panel_configuration/pages/dynamic-dashboard.adoc
docs/modules/panel_configuration/pages/expressions.adoc
docs/modules/panel_configuration/pages/forecasting.adoc

HELM-209: Datasource doc expansion

---

src/dashboards/cortex_flow_deep_dive.json
src/plugin.json

issue: https://issues.opennms.org/browse/NMS-13374
This PR adds "Cortex Flow Deep Dive" dashboard to the helm plugin that is similar to the existing "Flow Deep Dive" dashboard but gets all its data directly from Cortex.
The linked issue contains information how the environment can be setup to review this PR.

NMS-13374: Implement to show aggregation display on Grafana using data from Cortex

---

docs/modules/datasources/pages/flow_datasource.adoc
src/datasources/flow-ds/datasource.ts
src/datasources/flow-ds/flow_functions.ts
src/lib/client_delegate.ts
src/test/flow_ds_datasource.spec.ts

Issue: https://issues.opennms.org/browse/HELM-298

HELM-298: add withPrefix/withSuffix transformations

---

package-lock.json
package.json
src/datasources/perf-ds/datasource.ts
src/panels/alarm-table/table_model.ts
src/test/perf_ds_datasource.spec.ts

Issue: https://issues.opennms.org/browse/HELM-303

HELM-303: Use select resources endpoint when retrieving string properties and endpoint is available

---

src/datasources/entity-ds/Entity.ts
src/datasources/entity-ds/datasource.ts
src/datasources/entity-ds/query-directive.ts
src/datasources/entity-ds/query_ctrl.ts
src/datasources/perf-ds/datasource.ts
src/datasources/perf-ds/query_ctrl.ts
src/lib/client_delegate.ts
src/lib/query_variable.ts
src/lib/text_box_variable.ts
src/lib/utils.ts
src/panels/alarm-table/context_menu.ts
src/panels/alarm-table/editor.ts
src/panels/filter-panel/ctrl.ts
src/panels/filter-panel/editor.ts
src/panels/filter-panel/value_select_dropdown.ts
src/test/entity_ds_datasource.spec.ts
src/test/flow_ds_datasource.spec.ts
src/test/perf_ds_datasource.spec.ts

Issue: https://issues.opennms.org/browse/HELM-301
Grafana no more requires the use of special Angular promises; standard promises can be used.
I did some tests with the flow data source. However, the other functionalities of helm have still to be tested.

HELM-301: get rid of angular.IQService and angular.IPromise

---

docs/modules/contributing/pages/developing.adoc

This PR adds some stuff for helping to get set up for development.

add some documentation for setting up Helm development

---

src/datasources/flow-ds/datasource.ts
src/datasources/flow-ds/flow_functions.ts
src/lib/utils.ts
src/test/flow_ds_datasource.spec.ts

Added a new Transform swapIngressEgress to flows timeseries and table panels.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-311

HELM-311: Add a transform to swap Ingress and Egress

---

docs/modules/datasources/pages/flow_datasource.adoc

Added proposed fix to typo in Helm documentation
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-315

HELM-315: Document resource label changes, fix typo

---

src/datasources/flow-ds/datasource.ts
src/lib/utils.ts
src/test/flow_ds_datasource.spec.ts

Added template variable functionality to filter Nodes by Location in Flows datasource. Similar to Performance ticket HELM-307
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-318

HELM-318: Grafana Location Dashboard - Flows

---

docs/modules/datasources/pages/performance_datasource.adoc
src/datasources/perf-ds/datasource.ts
src/lib/utils.ts

Added a template variable nodeLocation that should allow norrow down nodes by location. This is meant to used together with nodeFilter so the selectable nodes are filtered by location.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-307

HELM-307: Grafana Location Dashboard - Performance

---

docs/modules/datasources/pages/entity_datasource.adoc
docs/modules/datasources/pages/flow_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc

Added documentation and examples for new location() template variable
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-326

HELM-326: Add documentation for location() template_variable

---

src/datasources/perf-ds/query_ctrl.ts

reverted some changes from HELM-301 that affected the query control in Perf DS
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-327

HELM-327: Performnce DS Query type Attribute selector broken

---

docs/modules/datasources/pages/flow_datasource.adoc

Added documentation for flow filtering expression requirement HELM-317
This review needs to wait until final approval of HELM-317.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-325

HELM-325: Document Grafana datasource expressions - Flows

---

docs/modules/installation/pages/requirements.adoc

NMS-13484: Document the Grafana Image Renderer plugin's dependencies - documented that dependency exists and then link to the full dependency list.
At that time, if …

NMS-13484: Document the Grafana Image Renderer plugin's dependencies

---

.github/assign-by-files.yml
.github/label-pr.yml
.github/workflows/auto-assign.yml
.github/workflows/labeler.yml

This is bringing over the GitHub actions for automatic doc review from the main repo.

bring docs actions from main repo

---

src/lib/text_box_variable.ts
src/lib/utils.ts

Targeting changes in https://github.com/OpenNMS/opennms-helm/pull/453 to the `release-8.x` branch.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-272

HELM-272: Targeting release-8.x branch

---

package-lock.json
package.json
src/datasources/entity-ds/SnmpInterfaceEntity.ts

Added NodeId to SnmpInterface DAO in Entity DS. 
Depends on opennms-js HELM-334 PR
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-334

HELM-334: Entity Datasource does not provide node information

---

docs/modules/datasources/pages/performance_datasource.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-351

HELM-351: nodeResources doc update

---

src/datasources/flow-ds/datasource.ts
src/lib/utils.ts
src/test/flow_ds_datasource.spec.ts

fix: added support to interpret interfaceSnmp resource as ifindex from perf datasource into flows datasource
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-333:

HELM-333: Possible fix when passing snmp interfaces from Perf DS to Flow filters

---

.circleci/config.yml
src/datasources/flow-ds/datasource.ts
src/panels/flow-histogram/ctrl.ts
src/test/flow_ds_datasource.spec.ts

fix: modified Flow Histogram panel metadata so it can identify metric and toBit transformations to render data.
Updated unit tests accordingly since there is more metadata passed by the Flow datasource.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-353

HELM-353: Fix Helm Flow Histogram Panel

---

src/datasources/entity-ds/partials/config.html

Slight adjustments to wording.  Let me know if I need to do anything specific for this.  It's pretty minor but it's my first commit here so go easy on me.
At that …

Fixed minor typos in description.

---

.circleci/config.yml
docs/modules/datasources/pages/performance_datasource.adoc
package-lock.json
package.json
src/datasources/entity-ds-react/EntityClauseEditor.tsx
src/datasources/entity-ds-react/EntityDataSource.ts
src/datasources/entity-ds-react/EntityHelper.tsx
src/datasources/entity-ds-react/EntityQueryEditor.tsx
src/datasources/flow-ds/datasource.ts
src/lib/utils.ts
src/panels/flow-histogram/ctrl.ts
src/test/flow_ds_datasource.spec.ts
webpack.config.js

This is a proof of concept PR for variables within the Entity Data source. This is meant to be a hand-off PR so that Scott Theleman can see what has been updated last week before him starting in on the Entity Datasource conversion this week. There is still a lot of work left to be done with grafana variables, this work is not complete.
It also looks like Alberto's code is in here too that he's been working on.
This has also been merged with the develop branch, to bring us back in line with the main release.
One or more reviewers should be …

Helm React Upgrade: Proof of Concept Entity Variables

---

src/datasources/entity-ds-react/EntityHelper.tsx
src/datasources/entity-ds-react/EntityOrderByEditor.tsx
src/datasources/entity-ds-react/EntityQueryEditor.tsx
src/datasources/entity-ds-react/useEntityProperties.ts
src/lib/client_delegate.ts

Port Entity Datasource Query Editor to React: Fix OrderBy, Limit, Featured Attributes
Will do additional testing and may need to fix a few more things (e.g. hook to reset `EntityOrderByEditor` state), but most functionality is working.
Also fixed small issue where IP Interface API calls were being made with empty clauses, causing 500 errors.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-354

HELM-354: Entity Datasource Query Editor: OrderBy, Limit, Featured Attributes

---

src/datasources/flow-ds-react/FlowDataSource.ts
src/datasources/flow-ds-react/FlowQueryEditor.tsx
src/datasources/flow-ds-react/helpers.ts
src/panels/flow-histogram-react/FlowHistogramContants.ts
src/panels/flow-histogram-react/FlowHistogramControl.tsx
src/panels/flow-histogram-react/FlowHistogramHelpers.ts
src/panels/flow-histogram-react/FlowHistogramOptions.tsx
src/panels/flow-histogram-react/FlowHistogramTypes.ts
src/test/react/flow_ds_datasource.spec.ts

This work is in addition to the main work that @scthompsonopen did as part of the migration into REACT
Things that needed some additions was implementing data layout as previous panel (Angular)
Displaying Stacked and Separated modes (barcharts)
Displaying Horizontal and Vertical (Stacked and Separated) orientation
Displaying Units (Bits, Kb, Mb, Gb or Bytes, KB, MB and GB) aswell and the labeling
Represent all Flows datasource transformations
Display  legend similarly as the angular version (Under Graph or on Right side of graph)
https://user-images.githubusercontent.com/3297292/213775993-c8b43120-cbed-49c6-a5bc-a2fd05394172.mp4
2. update the JIRA link at the bottom of this comment to refer …

HELM-352: Convert Flow Panel to React

---

src/constants/constants.ts
src/datasources/entity-ds-react/EntityDataSource.ts
src/datasources/entity-ds-react/queries/queryAlarms.ts
src/datasources/entity-ds-react/queries/queryBuilder.ts
src/panels/filter-panel-react/FilterPanelControl.tsx

Several fixes to the React FilterPanel and React Entity DataSource.
- fix Alarm Severities mapping in Entity DS
- add mapping for Alarm `isAcknowledged` column
- FilterPanel, add 'All' to Single select dropdown 
- FilterPanel, ensure metric values display in dropdowns
* JIRA (Issue Tracker): [HELM-354](https://opennms.atlassian.net/browse/HELM-354)
[HELM-354]: https://opennms.atlassian.net/browse/HELM-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HELM-354: Various React FilterPanel and EntityDS fixes

---

.vscode/settings.json
docs/modules/ROOT/nav.adoc
docs/modules/datasources/pages/entity_datasource.adoc
docs/modules/datasources/pages/flow_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc

- Update `datasources/performance_datasource.adoc,` `/entity_datasource.adoc`, `/flow_datasource.adoc`
- Update `ROOT/nav.adoc`
At that time, if you have commit access …

HELM-248: Document Filters

---

src/datasources/entity-ds-react/EntityDataSource.ts
src/datasources/flow-ds-react/FlowDataSource.ts
src/datasources/perf-ds-react/PerformanceDataSource.tsx
src/lib/client_delegate.ts
src/lib/utils.ts
src/panels/alarm-table-react/hooks/useAlarmHelmProperties.ts

Fixes error when testing datasources configuration
Fixes error when adding alarm-table panel without entities datasource
At that time, if you have commit access (are …

Helm react datasources and alarm table fixes

---

package-lock.json
src/datasources/entity-ds/EntityDataSource.ts
src/datasources/entity-ds/queries/queryAlarms.ts
src/datasources/entity-ds/queries/queryBuilder.ts
src/datasources/flow-ds/FlowDataSource.ts
src/datasources/flow-ds/constants.ts
src/datasources/flow-ds/helpers.ts
src/datasources/perf-ds/PerformanceDataSource.tsx
src/datasources/perf-ds/PerformanceHelpers.ts
src/datasources/perf-ds/queries/queryStringProperties.ts
src/panels/dashboard-convert/convert.ts
src/panels/flow-histogram/FlowHistogramControl.tsx
src/panels/flow-histogram/FlowHistogramHelpers.ts

Address most of the Sonar "code smell" issues and some refactoring to reduce cognitive complexity in various functions.
Seems that the security hotspot issues previously raised and captured in HELM-379 may have been fixed by a previous PR.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-381, https://opennms.atlassian.net/browse/HELM-379

HELM-381: Fix Sonar issues

---

docs/modules/about/pages/introduction.adoc

- Update `about/introduction.adoc`
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome …

HELM-378: Add flow management to introduction.adoc

---

src/lib/dashboard-convert/flowDs.ts
src/lib/dashboard-convert/flowHistogramPanel.ts
src/lib/dashboard-convert/panels.ts
src/panels/flow-histogram/FlowHistogramControl.tsx
src/panels/flow-histogram/FlowHistogramHelpers.ts

Update conversion tool to convert the Flow Histogram panel, as well as some updates to converting the Flow Datasource.
Most likely more work will be needed.
Also update `validateFlowHistogramPanelData` behavior to always return a `boolean` and display error info in the console, and to just not plot the `FlowHistogram` if there is no data or invalid data, vs. throwing an error.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

HELM-392: Convert Flow Histogram, some updates to Flow DS

---

src/datasources/perf-ds/PerformanceDataSource.tsx
src/datasources/perf-ds/PerformanceHelpers.ts
src/datasources/perf-ds/PerformanceQueryEditor.tsx
src/datasources/perf-ds/PerformanceStringProperty.tsx
src/datasources/perf-ds/queries/queryStringProperties.ts
src/datasources/perf-ds/types.ts
src/lib/api_types.ts
src/lib/dashboard-convert/utils.ts
src/lib/utils.ts
src/test/react/flow_ds_datasource.spec.ts

- feat: allow resources template variable to select multiple values. 
- Removed types that are not completely matching the scenarios to be handled. We should add correct types once we understand exactly what their intent is. 
Once the reviewer(s) accept the PR and the branch passes …

Allow Perf DS / String Props multiple values for Resources and Nodes

---

package-lock.json
src/panels/alarm-table/AlarmTableControl.tsx
src/panels/alarm-table/AlarmTableMenu.tsx
src/panels/alarm-table/hooks/useAlarmTableMenu.ts
src/panels/alarm-table/hooks/useAlarmTableMenuActions.ts
src/panels/alarm-table/hooks/useAlarmTableSelection.ts

The Alarm Table Panel appeared to 'freeze' after clicking it a few times. This was caused by some issues with how event handlers were being added.
This PR fixes that issue, but note if you for example change the data range using the Grafana controls, you will get new data, but event handlers won't be attached and you need to refresh the browser window to get the click / context menu functionality back. Will need to fix this.
This also pushes an updated `package-lock.json` to make sure the plugin names are in sync with `package.json`.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-395

HELM-395: Fix issue with Alarm Table Panel 'freezing'

---

src/datasources/perf-ds/PerformanceDataSource.tsx
src/panels/alarm-table/AlarmTableControl.tsx
src/panels/alarm-table/hooks/useAlarm.ts
src/panels/alarm-table/hooks/useAlarmProperties.ts

Fix some issues when Alarm Table panel is chosen but a datasource other than Entity Datasource is selected.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-397

HELM-397: Alarm Table issues when datasource not Entity

---

package-lock.json
package.json

they are no longer updating npm, just distributing through another CDN

update XLSX to latest version

---

.circleci/config.yml

This PR adds plugin and docker image trivy validation to the grafana plugin workflow.

Plugin and Docker Validation

---

src/dashboards/dashboard_converter.json
src/plugin.json

Include a "Converter" dashboard as one of the built-ins. This include the "Dashboard Convert" panel plus some instructions.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-432

HELM-432: Converter dashboard

---

README.md

Added top-line redirect to OPG successor plugin

---

docs/modules/getting_started/pages/importing.adoc
docs/modules/installation/pages/upgrading.adoc
site.yml

HELM-416: Docs about Predefined Dashboards are misleading

---

src/datasources/flow-ds/FlowDataSource.ts
src/datasources/flow-ds/constants.ts
src/datasources/flow-ds/helpers.ts
src/panels/flow-histogram/FlowHistogramConstants.ts
src/panels/flow-histogram/FlowHistogramHelpers.ts
src/panels/flow-histogram/FlowHistogramTypes.ts

A number of code improvements related to the Flow Datasource and Flow Histogram panel which were requested on PR #597 , including:
- breaking functions down into smaller chunks
- removing `moment.js` reference and `eslint-disable` clause
- type annotations
- other code cleanup and comments
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-369

HELM-369: Flow datasource and histogram panel code improvements

---

src/datasources/entity-ds/queries/queryNodes.ts

OPG-460: Add SNMP Primary ifindex and Primary IP Address to node table results
These column values weren't included, causing Categories values to display under SNMP ifIndex column.
Pulled in the logic from v8 to get these values.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/OPG-460

OPG-460: Add SNMP Primary ifindex and Primary IP Address to node table

---

src/datasources/entity-ds/EntityQueryEditor.tsx
src/datasources/entity-ds/queries/queryBuilder.ts
src/lib/utils.ts
src/test/react/lib_utils.spec.ts

Entity DS query editor was not retaining the Limit when it was changed to 0.
Also added/updated some relevant unit tests.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/OPG-463

OPG-463: EntityDS retain limit of 0. Add relevant unit tests

---

docs/modules/ROOT/pages/index.adoc
docs/modules/about/pages/introduction.adoc
docs/modules/contributing/pages/developing.adoc
docs/modules/contributing/pages/how-to-build-docs.adoc
docs/modules/datasources/pages/entity_datasource.adoc
docs/modules/datasources/pages/flow_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc
docs/modules/getting_started/pages/basic_walkthrough.adoc
docs/modules/getting_started/pages/dashboard_planning.adoc
docs/modules/getting_started/pages/flow-deep-dive.adoc
docs/modules/getting_started/pages/importing.adoc
docs/modules/getting_started/pages/index.adoc
docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
docs/modules/installation/pages/package.adoc
docs/modules/installation/pages/plugin.adoc
docs/modules/installation/pages/requirements.adoc
docs/modules/installation/pages/source.adoc
docs/modules/installation/pages/upgrading.adoc
docs/modules/panel_configuration/pages/dynamic-dashboard.adoc
docs/modules/panel_configuration/pages/expressions.adoc
docs/modules/panel_configuration/pages/forecasting.adoc
docs/modules/panel_configuration/pages/index.adoc
docs/modules/reference/pages/how-to-build-with-docker.adoc
docs/modules/reference/pages/severities.adoc

Added meta descriptions to the Plugin for Grafana documentation for better SEO.
At that time, if you have commit access (are an OpenNMS Group employee or a member of …

DP-84: Add meta descriptions to each page in the Alec & Helm docs

---

docs/modules/ROOT/pages/index.adoc

DP-83: Add doc information to each product landing page - added version and last updated table to the landing page of the Plugin for Grafana docs.
At that time, if you …

DP-83: Add doc information to each product landing page

---

docs/modules/datasources/pages/entity_datasource.adoc
docs/modules/datasources/pages/performance_datasource.adoc
src/datasources/entity-ds/constants.ts

Documentation for the `nodeFilter` `labelFormat` and `valueFormat` feature, see PR #937 and PR #940 for more info. 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OPG-472

OPG-472: Documentation for nodeFilter label and value formatting

---

README.md

NMS-15588: Top-level Helm 8 README updated with breadcrumbs to plugin v9
